<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class ReferralViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();

        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_referral_view()
    {
        $response = $this->get('/referral/referral-programs');

        $response->assertStatus(200)->assertViewIs('ReferralProgram::referral_programs.index');
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_create_referral_view()
    {
        $response = $this->get('/referral/referral-programs/create');

        $response->assertStatus(200)->assertViewIs('ReferralProgram::referral_programs.create_edit');
    }
}
